org: gberdejo
service: user-port-confirmation

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node24
    platform: node
    external:
      - '@aws-sdk/*'

custom:
  stage: ${opt:stage, 'dev'}
  env: ${file(config/${self:custom.stage}.yml)}
  resource: lambda
  lambdaName: user-port-confirmation
  lambdaRoleArn: ${ssm:/${self:custom.stage}/ctv/iam/lambda-role-arn}
  project: ctv

provider:
  name: aws
  runtime: nodejs24.x
  stage: ${self:custom.stage}
  stackName: ${self:custom.project}-${self:custom.resource}-${self:custom.lambdaName}-${self:custom.stage}
  environment: ${self:custom.env}
  iam:
    role: ${self:custom.lambdaRoleArn}

functions: ${file(config/functions.yml)}

resources:
  Resources:
    userPostConfirmationLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:custom.project}-${self:custom.resource}-${self:custom.lambdaName}-${self:custom.stage}
        LogGroupClass: INFREQUENT_ACCESS
